name: Structural Time Series
description: California electricity demand forecasting with Prophet.
author: Cloudera Engineer
specification_version: 1.0
prototype_version: 1.0
date: "2020-10-14"
api_version: 1

environment_variables:
  EIA_API_KEY:
    default: "SUPER AWESOME EIA KEY"
    description: "EIA open data API key"
    prompt_user: false

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: install_deps.py
    arguments: None 
    cpu: 1
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: install_deps
    short_summary: Running install dependencies job.
    long_summary: >-
      Running the job to install dependencies.  Note that this requires at least 4GB of memory

  - type: create_job
    name: Train Simple Model
    entity_label: train_simple_model
    script: scripts/fit_simple_prophet_model.py
    arguments: None
    short_summary: Job to train and export simple prophet model.
    long_summary: Job to train and export simple prophet model. Note that this requires at least 4GB of memory. 
    cpu: 1
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: train_simple_model
    short_summary: Running model training job.
    long_summary: >-
      Running the job to train the simple prophet model.

  - type: start_application
    name: Diagnostic app
    subdomain: diagnostics
    script: apps/launch_diagnostics.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
    
  - type: start_application
    name: Forecast app
    subdomain: forecast
    script: apps/launch_forecast.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3